In [1]:
# import libraries
import numpy as np
import pandas as pd

In [2]:
# load netindex dataset
nidf = pd.read_csv('net_index/city_daily_speeds.csv')
nidf.head().T

c:\users\tomzh\miniconda3\envs\ml\lib\site-packages\IPython\core\interactiveshell.py:3166: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,0,1,2,3,4
country,El Salvador,El Salvador,El Salvador,El Salvador,El Salvador
country_code,SV,SV,SV,SV,SV
region,San Salvador,San Salvador,San Salvador,San Salvador,San Salvador
region_code,10,10,10,10,10
city,San Salvador,San Salvador,San Salvador,San Salvador,San Salvador
date,2008-01-01,2008-01-02,2008-01-03,2008-01-04,2008-01-05
download_kbps,1121.51,1119.04,1120.72,1126.98,1123.01
upload_kbps,381.828,383.921,387.055,386.264,381.804
total_tests,4583,4631,4494,4331,4184
distance_miles,21.6485,21.3162,21.9008,22.0836,22.1806

In [3]:
# drop unwanted columns
nidf.drop(columns=['country_code', 'region_code'], inplace=True)
nidf.head().T

,0,1,2,3,4
country,El Salvador,El Salvador,El Salvador,El Salvador,El Salvador
region,San Salvador,San Salvador,San Salvador,San Salvador,San Salvador
city,San Salvador,San Salvador,San Salvador,San Salvador,San Salvador
date,2008-01-01,2008-01-02,2008-01-03,2008-01-04,2008-01-05
download_kbps,1121.51,1119.04,1120.72,1126.98,1123.01
upload_kbps,381.828,383.921,387.055,386.264,381.804
total_tests,4583,4631,4494,4331,4184
distance_miles,21.6485,21.3162,21.9008,22.0836,22.1806

In [5]:
# group by and calculate mean
nidf2 = nidf.groupby(['country', 'region', 'date']).agg({
    'download_kbps':'mean',
    'upload_kbps':'mean',
    'total_tests':'sum',
    'distance_miles': 'mean'
}).reset_index()

In [9]:
# write to file
nidf2.to_csv('net_index/region_daily_speeds.csv', index=False)